### ISSUE TITLE
可以加一下 onDescriptorReadRequest  描述的回调

### ISSUE THREAD

**Issue by Yuanarcheannovice** [zhzc0x/BluetoothClient#1]
onDescriptorReadRequest 相关api没有，建议加一下
源码我down下来自己加了；

**Comment by zhzc0x** [comment]
这块的需求我还没有遇到过，能贴下你加的代码吗？

**Comment by Yuanarcheannovice** [comment]
啊，不好拿代码，我换成这个用了，https://github.com/buhuiming/BleCore，这个确实强大，功能都有
