### ISSUE TITLE
可以考虑增加一下 ble的扫描过滤

### ISSUE THREAD

**Issue by Yuanarcheannovice** [zhzc0x/BluetoothClient#2]
// 设置扫描过滤器
        if (!serviceUUID?.toString().isNullOrEmpty()) {
            val serviceUuid = ParcelUuid.fromString(serviceUUID?.toString())
            val scanFilter = ScanFilter.Builder().setServiceUuid(serviceUuid).build()
            val filters = listOf(scanFilter)
            bluetoothAdapter!!.bluetoothLeScanner!!.startScan(
                filters, ScanSettings.Builder()
                    .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).build(), scanCallback
            )
        } else {
            bluetoothAdapter!!.bluetoothLeScanner!!.startScan(
                null, ScanSettings.Builder()
                    .setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).build(), scanCallback
            )
        }

**Comment by zhzc0x** [comment]
这个可以外在面通过device.name去处理过滤，内部不提供过滤条件设置
